"""
plot_32.py  -  Lab 3.2 Figures
================================
Run from repo root:
    python code/lab32/plot_32.py

Generates figures for the Lab 3.2 BERT experiments:
  - all embedding comparison if Lab 3.1 results are available
  - BERT voxel-wise CC distributions
  - fine-tuning / LoRA gains relative to pretrained BERT
  - cross-subject consistency of embedding rankings
  - voxel-wise cross-subject stability
"""

import os
import json
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch


ROOT = Path(__file__).resolve().parents[2]
RESULTS_DIR = Path(os.environ.get("RESULTS_DIR", ROOT / "results"))
RIDGE31_DIR = RESULTS_DIR / "ridge_31"
RIDGE32_DIR = RESULTS_DIR / "ridge_32"
METRIC_DIR = ROOT / "results" / "metrics"
FIG_DIR = ROOT / "figures" / "lab32"

METRIC_DIR.mkdir(parents=True, exist_ok=True)
FIG_DIR.mkdir(parents=True, exist_ok=True)

SUBJECTS = ["subject2", "subject3"]
SUBJECT_LABELS = {"subject2": "Subject 2", "subject3": "Subject 3"}

EMBEDDINGS_31 = ["bow", "glove", "word2vec"]
EMBEDDINGS_32 = ["bert_pretrained", "bert_finetuned", "bert_lora"]
EMBEDDINGS_ALL = EMBEDDINGS_31 + EMBEDDINGS_32

EMBEDDING_LABELS = {
    "bow": "BoW",
    "glove": "GloVe",
    "word2vec": "Word2Vec",
    "bert_pretrained": "BERT",
    "bert_finetuned": "BERT-FT",
    "bert_lora": "LoRA",
}

COLORS = {
    "bow": "#C8A87A",
    "glove": "#D6865E",
    "word2vec": "#B9734D",
    "bert_pretrained": "#4C86BD",
    "bert_finetuned": "#2D5F93",
    "bert_lora": "#5BAFA3",
}

SUBJECT_MARKERS = {"subject2": "o", "subject3": "s"}

METRICS = ["mean_cc", "median_cc", "top5_cc", "top1_cc"]
METRIC_LABELS = {
    "mean_cc": "Mean CC",
    "median_cc": "Median CC",
    "top5_cc": "Top 5% CC",
    "top1_cc": "Top 1% CC",
}

BERT_METHODS = ["bert_pretrained", "bert_finetuned", "bert_lora"]
WELL_PREDICTED_THRESHOLD = 0.10


plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "font.size": 11,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.linewidth": 0.8,
    "axes.grid": True,
    "grid.alpha": 0.25,
    "grid.linewidth": 0.6,
    "figure.dpi": 150,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
    "savefig.pad_inches": 0.12,
})

plt.rcParams["xtick.labelsize"] = 9
plt.rcParams["ytick.labelsize"] = 9


def metric_value(subject: str, embedding: str, metric: str) -> float:
    """Return one saved CC summary metric, or NaN when that run is unavailable."""
    stats = load_stats(subject, embedding)
    if stats is None:
        return np.nan
    return float(stats[metric])


def clean_axis(ax):
    """Apply the shared light-grid style used across Lab 3.2 figures."""
    ax.grid(True, axis="x", alpha=0.22)
    ax.grid(False, axis="y")


def add_context_split(ax, y_pos=None, orientation="horizontal"):
    """Draw the visual separator between static and contextual embeddings."""
    if orientation == "horizontal" and y_pos is not None:
        ax.axhline(y_pos, color="#BDBDBD", linestyle="--", linewidth=1.0, alpha=0.85)
    elif orientation == "vertical" and y_pos is not None:
        ax.axvline(y_pos, color="#BDBDBD", linestyle="--", linewidth=1.0, alpha=0.85)


def ridge_dir_for_embedding(embedding: str) -> Path:
    """Map an embedding name to the ridge output directory that owns it."""
    return RIDGE31_DIR if embedding in EMBEDDINGS_31 else RIDGE32_DIR


def stats_path(subject: str, embedding: str) -> Path:
    """Path to the JSON summary generated by the ridge script."""
    return ridge_dir_for_embedding(embedding) / f"{embedding}_{subject}_stats.json"


def corrs_path(subject: str, embedding: str) -> Path:
    """Path to voxel-wise held-out correlations for one subject/embedding."""
    return ridge_dir_for_embedding(embedding) / f"{embedding}_{subject}_corrs.npy"


def valphas_path(subject: str, embedding: str) -> Path:
    """Path to voxel-wise selected ridge alphas for one subject/embedding."""
    return ridge_dir_for_embedding(embedding) / f"{embedding}_{subject}_valphas.npy"


def load_stats(subject: str, embedding: str):
    """Load saved aggregate CC metrics; return None if the run is missing."""
    path = stats_path(subject, embedding)
    if not path.exists():
        return None
    with open(path) as fh:
        return json.load(fh)


def load_corrs(subject: str, embedding: str):
    """Memory-map voxel-wise CCs so large arrays are not copied unnecessarily."""
    path = corrs_path(subject, embedding)
    if not path.exists():
        return None
    return np.load(path, mmap_mode="r")


def load_valphas(subject: str, embedding: str):
    """Load selected ridge alphas for diagnostic plots."""
    path = valphas_path(subject, embedding)
    if not path.exists():
        return None
    return np.load(path, mmap_mode="r")


def available_embeddings(embeddings):
    """Filter a candidate embedding list to runs with at least one subject present."""
    available = []
    for embedding in embeddings:
        if any(stats_path(subject, embedding).exists() for subject in SUBJECTS):
            available.append(embedding)
    return available


def save_figure(fig, name: str):
    """Save each figure as both PNG for reports and PDF for high-quality export."""
    png = FIG_DIR / f"{name}.png"
    pdf = FIG_DIR / f"{name}.pdf"
    fig.savefig(png)
    fig.savefig(pdf)
    plt.close(fig)
    print(f"Saved: {png}")
    print(f"Saved: {pdf}")


def write_metric_tables():
    """Write compact CSV tables used directly in the report."""
    bert_rows = []
    all_rows = []

    for embedding in EMBEDDINGS_ALL:
        for subject in SUBJECTS:
            stats = load_stats(subject, embedding)
            if stats is None:
                continue
            row = {
                "subject": subject,
                "embedding": EMBEDDING_LABELS[embedding],
                "mean_cc": stats["mean_cc"],
                "median_cc": stats["median_cc"],
                "top5_cc": stats["top5_cc"],
                "top1_cc": stats["top1_cc"],
                "frac_pos": stats.get("frac_pos", np.nan),
            }
            all_rows.append(row)
            if embedding in EMBEDDINGS_32:
                bert_rows.append(row)

    def write_csv(path: Path, rows):
        with open(path, "w") as fh:
            fh.write("subject,embedding,mean_cc,median_cc,top5_cc,top1_cc,frac_pos\n")
            for row in rows:
                fh.write(
                    f"{row['subject']},{row['embedding']},"
                    f"{row['mean_cc']:.6f},{row['median_cc']:.6f},"
                    f"{row['top5_cc']:.6f},{row['top1_cc']:.6f},"
                    f"{row['frac_pos']:.6f}\n"
                )
        print(f"Saved: {path}")

    write_csv(METRIC_DIR / "cc_scores_32.csv", bert_rows)
    write_csv(METRIC_DIR / "cc_scores_all_embeddings.csv", all_rows)

    if bert_rows:
        print("\nLab 3.2 CC metrics")
        print(f"{'Subject':<12} {'Embedding':<16} {'Mean CC':>9} {'Median':>9} {'Top 5%':>9} {'Top 1%':>9}")
        print("-" * 72)
        for row in bert_rows:
            print(
                f"{row['subject']:<12} {row['embedding']:<16} "
                f"{row['mean_cc']:>9.4f} {row['median_cc']:>9.4f} "
                f"{row['top5_cc']:>9.4f} {row['top1_cc']:>9.4f}"
            )


def fig_bert_metric_summary():
    embeddings = available_embeddings(EMBEDDINGS_32)
    if not embeddings:
        print("Skipping BERT metric summary: no Lab 3.2 stats found.")
        return

    fig, axes = plt.subplots(1, 4, figsize=(17, 4.7), constrained_layout=True)
    x = np.arange(len(SUBJECTS))
    width = 0.24
    offsets = np.linspace(-width, width, len(embeddings))

    for ax, metric in zip(axes, METRICS):
        for offset, embedding in zip(offsets, embeddings):
            vals = [metric_value(subject, embedding, metric) for subject in SUBJECTS]
            bars = ax.bar(
                x + offset,
                vals,
                width=width,
                color=COLORS[embedding],
                edgecolor="white",
                linewidth=0.7,
                label=EMBEDDING_LABELS[embedding],
            )
            for bar, val in zip(bars, vals):
                if np.isfinite(val):
                    ax.text(
                        bar.get_x() + bar.get_width() / 2,
                        bar.get_height() + max(vals) * 0.025,
                        f"{val:.3f}",
                        ha="center",
                        va="bottom",
                        fontsize=7.8,
                    )

        ax.set_title(METRIC_LABELS[metric], fontsize=12, fontweight="bold")
        ax.set_xticks(x)
        ax.set_xticklabels([SUBJECT_LABELS[s] for s in SUBJECTS])
        ax.set_ylabel("Pearson r")
        ax.margins(y=0.24)
        ax.grid(True, axis="y", alpha=0.25)
        ax.grid(False, axis="x")

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=len(embeddings), frameon=False, bbox_to_anchor=(0.5, -0.06))
    fig.suptitle("Lab 3.2 BERT Encoding Performance", fontsize=16, fontweight="bold")
    save_figure(fig, "fig1_bert_metric_summary")


def fig_all_embeddings_hbars():
    embeddings = available_embeddings(EMBEDDINGS_ALL)
    if not embeddings:
        print("Skipping all-embedding horizontal bars: no stats found.")
        return

    fig, axes = plt.subplots(
        len(SUBJECTS),
        len(METRICS),
        figsize=(18, 7.8),
        sharey=True,
        constrained_layout=True,
    )
    if len(SUBJECTS) == 1:
        axes = axes[None, :]

    y = np.arange(len(embeddings))
    split_y = len(EMBEDDINGS_31) - 0.5 if all(e in embeddings for e in EMBEDDINGS_31) else None
    for row, subject in enumerate(SUBJECTS):
        for col, metric in enumerate(METRICS):
            ax = axes[row, col]
            vals = [metric_value(subject, embedding, metric) for embedding in embeddings]
            ax.barh(
                y,
                vals,
                color=[COLORS[e] for e in embeddings],
                edgecolor="white",
                linewidth=0.6,
            )
            if split_y is not None:
                add_context_split(ax, split_y, orientation="horizontal")
            for yi, val in zip(y, vals):
                if np.isfinite(val):
                    ax.text(val + max(vals) * 0.018, yi, f"{val:.3f}", va="center", fontsize=8.4)
            ax.set_title(METRIC_LABELS[metric], fontsize=12, fontweight="bold")
            ax.set_xlabel("Pearson r")
            if col == 0:
                ax.set_ylabel(SUBJECT_LABELS[subject], fontsize=12, fontweight="bold")
                ax.set_yticks(y)
                ax.set_yticklabels([EMBEDDING_LABELS[e] for e in embeddings])
            ax.invert_yaxis()
            ax.margins(x=0.12)
            clean_axis(ax)

    fig.suptitle("Voxel-Wise Prediction Accuracy Across All Embedding Methods", fontsize=16, fontweight="bold")
    save_figure(fig, "fig1_all_embeddings_hbars")


def fig_all_embedding_comparison():
    embeddings = available_embeddings(EMBEDDINGS_ALL)
    if not embeddings:
        print("Skipping all-embedding comparison: no stats found.")
        return

    fig, axes = plt.subplots(2, 2, figsize=(14, 8.5), constrained_layout=True)
    axes = axes.ravel()
    x = np.arange(len(embeddings))

    for ax, metric in zip(axes, METRICS):
        for subject in SUBJECTS:
            y = []
            x_found = []
            for i, embedding in enumerate(embeddings):
                stats = load_stats(subject, embedding)
                if stats is None:
                    continue
                x_found.append(i)
                y.append(stats[metric])
            if not y:
                continue
            ax.plot(
                x_found,
                y,
                color="#333333",
                alpha=0.35,
                linewidth=1.4,
                zorder=1,
            )
            for xi, yi, embedding in zip(x_found, y, [embeddings[i] for i in x_found]):
                ax.scatter(
                    xi,
                    yi,
                    s=72,
                    color=COLORS[embedding],
                    marker=SUBJECT_MARKERS[subject],
                    edgecolor="white",
                    linewidth=0.9,
                    zorder=3,
                )
                ax.text(xi, yi, f" {yi:.3f}", va="center", fontsize=8.2, color="#202020")

        ax.set_title(METRIC_LABELS[metric], fontsize=13, fontweight="bold")
        ax.set_xticks(x)
        ax.set_xticklabels([EMBEDDING_LABELS[e] for e in embeddings], rotation=28, ha="right")
        ax.set_ylabel("Pearson r")
        ax.margins(x=0.08, y=0.18)

    embedding_handles = [
        Line2D([0], [0], marker="o", color="none", label=EMBEDDING_LABELS[e],
               markerfacecolor=COLORS[e], markeredgecolor="white", markersize=8)
        for e in embeddings
    ]
    subject_handles = [
        Line2D([0], [0], marker=SUBJECT_MARKERS[s], color="#333333",
               label=SUBJECT_LABELS[s], linestyle="none", markersize=7)
        for s in SUBJECTS
    ]
    fig.legend(
        handles=embedding_handles + subject_handles,
        loc="lower center",
        ncol=min(len(embedding_handles) + len(subject_handles), 5),
        frameon=False,
        bbox_to_anchor=(0.5, -0.045),
    )
    fig.suptitle("Encoding Accuracy Across Embedding Families", fontsize=16, fontweight="bold")
    save_figure(fig, "fig1_all_embedding_comparison")


def fig_bert_voxel_distributions():
    embeddings = available_embeddings(EMBEDDINGS_32)
    if not embeddings:
        print("Skipping BERT distributions: no Lab 3.2 correlations found.")
        return

    fig, axes = plt.subplots(1, len(SUBJECTS), figsize=(13.5, 5.2), sharey=True, constrained_layout=True)
    if len(SUBJECTS) == 1:
        axes = [axes]

    for ax, subject in zip(axes, SUBJECTS):
        data = []
        labels = []
        colors = []
        for embedding in embeddings:
            corrs = load_corrs(subject, embedding)
            if corrs is None:
                continue
            data.append(np.asarray(corrs, dtype=np.float32))
            labels.append(EMBEDDING_LABELS[embedding])
            colors.append(COLORS[embedding])

        if not data:
            ax.set_visible(False)
            continue

        box = ax.boxplot(
            data,
            patch_artist=True,
            showfliers=False,
            widths=0.58,
            medianprops={"color": "#111111", "linewidth": 1.6},
            whiskerprops={"color": "#555555", "linewidth": 1.0},
            capprops={"color": "#555555", "linewidth": 1.0},
        )
        for patch, color in zip(box["boxes"], colors):
            patch.set_facecolor(color)
            patch.set_edgecolor("#2A2A2A")
            patch.set_alpha(0.75)

        for i, corrs in enumerate(data, start=1):
            p95 = np.percentile(corrs, 95)
            p99 = np.percentile(corrs, 99)
            ax.scatter([i], [p95], marker="D", s=34, color="white", edgecolor="#111111", zorder=3)
            ax.scatter([i], [p99], marker="^", s=44, color="#111111", edgecolor="white", zorder=3)
            ax.text(i + 0.08, p99, f"{p99:.3f}", fontsize=8.5, va="center")

        ax.axhline(0.10, color="#D00000", linestyle="--", linewidth=1.1, alpha=0.8)
        ax.text(0.55, 0.103, "CC = 0.10", color="#D00000", fontsize=8.5, va="bottom")
        ax.set_title(SUBJECT_LABELS[subject], fontsize=13, fontweight="bold")
        ax.set_xticks(np.arange(1, len(labels) + 1))
        ax.set_xticklabels(labels, rotation=20, ha="right")
        ax.set_ylabel("Voxel-wise held-out CC")
        ax.set_ylim(-0.18, 0.28)

    fig.suptitle("Voxel-Wise Predictive Accuracy for BERT Variants", fontsize=16, fontweight="bold")
    save_figure(fig, "fig2_bert_voxel_distributions")
    save_figure_alias("fig2_bert_voxel_distributions", "cc_distributions_bert")


def save_figure_alias(source_name: str, alias_name: str):
    for ext in ["png", "pdf"]:
        source = FIG_DIR / f"{source_name}.{ext}"
        alias = FIG_DIR / f"{alias_name}.{ext}"
        if source.exists():
            alias.write_bytes(source.read_bytes())
            print(f"Saved: {alias}")


def fig_bert_delta_from_pretrained():
    comparisons = [
        ("bert_finetuned", "BERT-FT - BERT"),
        ("bert_lora", "LoRA - BERT"),
    ]

    if not all(corrs_path(subject, "bert_pretrained").exists() for subject in SUBJECTS):
        print("Skipping delta figure: pretrained BERT correlations are missing.")
        return

    fig, axes = plt.subplots(2, len(SUBJECTS), figsize=(13.5, 7.6), sharex=True, constrained_layout=True)
    if len(SUBJECTS) == 1:
        axes = axes[:, None]

    bins = np.linspace(-0.08, 0.08, 90)
    for col, subject in enumerate(SUBJECTS):
        base = np.asarray(load_corrs(subject, "bert_pretrained"), dtype=np.float32)
        for row, (embedding, label) in enumerate(comparisons):
            ax = axes[row, col]
            corrs = load_corrs(subject, embedding)
            if corrs is None:
                ax.set_visible(False)
                continue
            delta = np.asarray(corrs, dtype=np.float32) - base
            improved = 100.0 * float((delta > 0).mean())
            mean_delta = float(delta.mean())

            ax.hist(delta, bins=bins, color=COLORS[embedding], alpha=0.78, density=True)
            ax.axvline(0, color="#111111", linewidth=1.1)
            ax.axvline(mean_delta, color="#FFFFFF", linewidth=2.2)
            ax.axvline(mean_delta, color="#111111", linewidth=0.9, linestyle="--")
            ax.set_title(f"{SUBJECT_LABELS[subject]}: {label}", fontsize=12, fontweight="bold")
            ax.set_xlabel("Change in voxel CC")
            ax.set_ylabel("Density")
            ax.text(
                0.02,
                0.92,
                f"mean delta = {mean_delta:+.4f}\nvoxels improved = {improved:.1f}%",
                transform=ax.transAxes,
                va="top",
                ha="left",
                fontsize=9.5,
                bbox={"facecolor": "white", "edgecolor": "#D9D9D9", "boxstyle": "round,pad=0.28"},
            )

    fig.suptitle("Does Fine-Tuning Improve Individual Voxels?", fontsize=16, fontweight="bold")
    save_figure(fig, "fig3_bert_delta_from_pretrained")


def fig_well_predicted_voxel_overlap():
    embeddings = [e for e in BERT_METHODS if all(corrs_path(s, e).exists() for s in SUBJECTS)]
    if len(embeddings) < 2:
        print("Skipping well-predicted overlap: need at least two BERT correlation files for both subjects.")
        return

    fig, axes = plt.subplots(1, len(SUBJECTS), figsize=(7.2 * len(SUBJECTS), 5.2), constrained_layout=True)
    if len(SUBJECTS) == 1:
        axes = [axes]

    patterns = [
        ("BERT only", (1, 0, 0)),
        ("BERT-FT only", (0, 1, 0)),
        ("LoRA only", (0, 0, 1)),
        ("BERT + BERT-FT", (1, 1, 0)),
        ("BERT + LoRA", (1, 0, 1)),
        ("BERT-FT + LoRA", (0, 1, 1)),
        ("All three", (1, 1, 1)),
    ]

    for ax, subject in zip(axes, SUBJECTS):
        masks = []
        for embedding in BERT_METHODS:
            corrs = load_corrs(subject, embedding)
            if corrs is None:
                masks.append(np.zeros(0, dtype=bool))
            else:
                masks.append(np.asarray(corrs) >= WELL_PREDICTED_THRESHOLD)
        n = min(len(mask) for mask in masks)
        masks = [mask[:n] for mask in masks]

        counts = []
        for _, pattern in patterns:
            keep = np.ones(n, dtype=bool)
            for mask, flag in zip(masks, pattern):
                keep &= mask if flag else ~mask
            counts.append(int(keep.sum()))

        colors = ["#4C86BD", "#2D5F93", "#5BAFA3", "#6B8FBF", "#6FB4C0", "#4F8F9A", "#303030"]
        y = np.arange(len(patterns))
        ax.barh(y, counts, color=colors, edgecolor="white", linewidth=0.7)
        ax.set_yticks(y)
        ax.set_yticklabels([p[0] for p in patterns])
        ax.invert_yaxis()
        ax.set_xlabel(f"Voxels with CC >= {WELL_PREDICTED_THRESHOLD:.2f}")
        ax.set_title(SUBJECT_LABELS[subject], fontsize=13, fontweight="bold")
        ax.grid(True, axis="x", alpha=0.25)
        ax.grid(False, axis="y")
        for yi, count in zip(y, counts):
            ax.text(count + max(counts + [1]) * 0.015, yi, str(count), va="center", fontsize=9)

    fig.suptitle("Overlap of Well-Predicted Voxels Across BERT Variants", fontsize=16, fontweight="bold")
    save_figure(fig, "fig5_well_predicted_voxel_overlap")


def fig_finetuning_win_loss_summary():
    comparisons = [("bert_finetuned", "BERT-FT vs BERT"), ("bert_lora", "LoRA vs BERT")]
    if not all(corrs_path(subject, "bert_pretrained").exists() for subject in SUBJECTS):
        print("Skipping win/loss summary: pretrained BERT correlations are missing.")
        return

    fig, axes = plt.subplots(1, len(SUBJECTS), figsize=(7.0 * len(SUBJECTS), 5.0), sharey=True, constrained_layout=True)
    if len(SUBJECTS) == 1:
        axes = [axes]

    labels = ["Improved", "Unchanged", "Worse"]
    colors = ["#2E8B57", "#BDBDBD", "#C44E52"]

    for ax, subject in zip(axes, SUBJECTS):
        base = np.asarray(load_corrs(subject, "bert_pretrained"), dtype=np.float32)
        x = np.arange(len(comparisons))
        bottom = np.zeros(len(comparisons))
        for label, color, category in zip(labels, colors, ["improved", "same", "worse"]):
            vals = []
            for embedding, _ in comparisons:
                corrs = load_corrs(subject, embedding)
                if corrs is None:
                    vals.append(np.nan)
                    continue
                delta = np.asarray(corrs, dtype=np.float32)[: len(base)] - base[: len(corrs)]
                eps = 1e-6
                if category == "improved":
                    vals.append(100.0 * float((delta > eps).mean()))
                elif category == "same":
                    vals.append(100.0 * float((np.abs(delta) <= eps).mean()))
                else:
                    vals.append(100.0 * float((delta < -eps).mean()))
            ax.bar(x, vals, bottom=bottom, color=color, edgecolor="white", linewidth=0.7, label=label)
            bottom += np.nan_to_num(vals)

        ax.set_xticks(x)
        ax.set_xticklabels([name for _, name in comparisons], rotation=15, ha="right")
        ax.set_ylabel("Percent of voxels")
        ax.set_ylim(0, 100)
        ax.set_title(SUBJECT_LABELS[subject], fontsize=13, fontweight="bold")
        ax.grid(True, axis="y", alpha=0.25)
        ax.grid(False, axis="x")

    handles = [Patch(facecolor=c, edgecolor="white", label=l) for l, c in zip(labels, colors)]
    fig.legend(handles=handles, loc="lower center", ncol=3, frameon=False, bbox_to_anchor=(0.5, -0.04))
    fig.suptitle("Fine-Tuning Win/Loss Relative to Pretrained BERT", fontsize=16, fontweight="bold")
    save_figure(fig, "fig5_finetuning_win_loss_summary")


def fig_pretrained_vs_finetuned_scatter():
    comparisons = [("bert_finetuned", "BERT-FT"), ("bert_lora", "LoRA")]
    if not all(corrs_path(subject, "bert_pretrained").exists() for subject in SUBJECTS):
        print("Skipping pretrained-vs-finetuned scatter: pretrained BERT correlations are missing.")
        return

    fig, axes = plt.subplots(len(SUBJECTS), len(comparisons), figsize=(12.5, 9.5), constrained_layout=True)
    if len(SUBJECTS) == 1:
        axes = axes[None, :]

    for row, subject in enumerate(SUBJECTS):
        base = np.asarray(load_corrs(subject, "bert_pretrained"), dtype=np.float32)
        for col, (embedding, label) in enumerate(comparisons):
            ax = axes[row, col]
            corrs = load_corrs(subject, embedding)
            if corrs is None:
                ax.set_visible(False)
                continue
            comp = np.asarray(corrs, dtype=np.float32)
            n = min(len(base), len(comp))
            x = base[:n]
            y = comp[:n]
            lo = float(min(np.percentile(x, 0.2), np.percentile(y, 0.2)))
            hi = float(max(np.percentile(x, 99.8), np.percentile(y, 99.8)))
            pad = 0.08 * (hi - lo)
            lo -= pad
            hi += pad
            ax.hist2d(x, y, bins=90, range=[[lo, hi], [lo, hi]], cmap="Blues", cmin=1)
            ax.plot([lo, hi], [lo, hi], color="#E63946", linestyle="--", linewidth=1.1)
            improved = 100.0 * float((y > x).mean())
            mean_delta = float((y - x).mean())
            ax.text(
                0.04,
                0.95,
                f"improved={improved:.1f}%\nmean delta={mean_delta:+.4f}",
                transform=ax.transAxes,
                va="top",
                fontsize=9,
                bbox={"facecolor": "white", "edgecolor": "#D9D9D9", "boxstyle": "round,pad=0.25"},
            )
            ax.set_title(f"{SUBJECT_LABELS[subject]}: {label} vs BERT", fontsize=12, fontweight="bold")
            ax.set_xlabel("Pretrained BERT voxel CC")
            ax.set_ylabel(f"{label} voxel CC")
            ax.set_xlim(lo, hi)
            ax.set_ylim(lo, hi)

    fig.suptitle("Voxel-Level Effect of Fine-Tuning", fontsize=16, fontweight="bold")
    save_figure(fig, "fig5_pretrained_vs_finetuned_scatter")


def fig_top_voxel_rank_stability(k_frac: float = 0.01):
    embeddings = [e for e in BERT_METHODS if all(corrs_path(s, e).exists() for s in SUBJECTS)]
    if len(embeddings) < 2:
        print("Skipping top-voxel stability: need at least two BERT correlation files for both subjects.")
        return

    pairs = [
        ("bert_pretrained", "bert_finetuned"),
        ("bert_pretrained", "bert_lora"),
        ("bert_finetuned", "bert_lora"),
    ]
    fig, axes = plt.subplots(1, len(SUBJECTS), figsize=(7.0 * len(SUBJECTS), 5.0), sharey=True, constrained_layout=True)
    if len(SUBJECTS) == 1:
        axes = [axes]

    for ax, subject in zip(axes, SUBJECTS):
        overlaps = []
        labels = []
        for a, b in pairs:
            ca = load_corrs(subject, a)
            cb = load_corrs(subject, b)
            if ca is None or cb is None:
                continue
            ca = np.asarray(ca, dtype=np.float32)
            cb = np.asarray(cb, dtype=np.float32)
            n = min(len(ca), len(cb))
            k = max(1, int(np.floor(k_frac * n)))
            top_a = set(np.argsort(ca[:n])[-k:])
            top_b = set(np.argsort(cb[:n])[-k:])
            overlap = len(top_a & top_b) / len(top_a | top_b)
            overlaps.append(overlap)
            labels.append(f"{EMBEDDING_LABELS[a]}\nvs\n{EMBEDDING_LABELS[b]}")
        x = np.arange(len(labels))
        ax.bar(x, overlaps, color="#6A7FDB", edgecolor="white", linewidth=0.7)
        ax.set_xticks(x)
        ax.set_xticklabels(labels)
        ax.set_ylim(0, 1)
        ax.set_ylabel("Jaccard overlap")
        ax.set_title(SUBJECT_LABELS[subject], fontsize=13, fontweight="bold")
        ax.grid(True, axis="y", alpha=0.25)
        ax.grid(False, axis="x")
        for xi, val in zip(x, overlaps):
            ax.text(xi, val + 0.025, f"{val:.2f}", ha="center", fontsize=9)

    fig.suptitle(f"Top {int(k_frac * 100)}% Voxel Rank Stability Across BERT Variants", fontsize=16, fontweight="bold")
    save_figure(fig, "fig5_top_voxel_rank_stability")


def fig_alpha_distributions():
    embeddings = available_embeddings(EMBEDDINGS_ALL)
    embeddings = [e for e in embeddings if any(valphas_path(s, e).exists() for s in SUBJECTS)]
    if not embeddings:
        print("Skipping alpha distributions: no valphas files found.")
        return

    fig, axes = plt.subplots(len(SUBJECTS), 1, figsize=(14, 7.2), sharex=True, constrained_layout=True)
    if len(SUBJECTS) == 1:
        axes = [axes]

    for ax, subject in zip(axes, SUBJECTS):
        data = []
        labels = []
        colors = []
        for embedding in embeddings:
            valphas = load_valphas(subject, embedding)
            if valphas is None:
                continue
            vals = np.asarray(valphas, dtype=np.float64)
            vals = vals[np.isfinite(vals) & (vals > 0)]
            if len(vals) == 0:
                continue
            data.append(np.log10(vals))
            labels.append(EMBEDDING_LABELS[embedding])
            colors.append(COLORS[embedding])

        if not data:
            ax.set_visible(False)
            continue

        box = ax.boxplot(
            data,
            patch_artist=True,
            showfliers=False,
            widths=0.58,
            medianprops={"color": "#111111", "linewidth": 1.5},
            whiskerprops={"color": "#555555", "linewidth": 1.0},
            capprops={"color": "#555555", "linewidth": 1.0},
        )
        for patch, color in zip(box["boxes"], colors):
            patch.set_facecolor(color)
            patch.set_edgecolor("#2A2A2A")
            patch.set_alpha(0.75)
        ax.set_xticks(np.arange(1, len(labels) + 1))
        ax.set_xticklabels(labels, rotation=25, ha="right")
        ax.set_ylabel(r"Selected $\log_{10}(\alpha)$")
        ax.set_title(SUBJECT_LABELS[subject], fontsize=13, fontweight="bold")
        ax.grid(True, axis="y", alpha=0.25)
        ax.grid(False, axis="x")

    fig.suptitle("Distribution of Voxel-Specific Ridge Regularization", fontsize=16, fontweight="bold")
    save_figure(fig, "fig5_alpha_distributions")


def fig_embedding_family_summary():
    families = {
        "Lexical": ["bow"],
        "Static semantic": ["glove", "word2vec"],
        "Contextual BERT": ["bert_pretrained", "bert_finetuned", "bert_lora"],
    }
    available = set(available_embeddings(EMBEDDINGS_ALL))
    if not available:
        print("Skipping family summary: no stats found.")
        return

    fig, axes = plt.subplots(1, len(METRICS), figsize=(17, 4.8), constrained_layout=True)
    family_colors = {"Lexical": "#C8A87A", "Static semantic": "#D6865E", "Contextual BERT": "#4C86BD"}

    for ax, metric in zip(axes, METRICS):
        labels = []
        means = []
        lows = []
        highs = []
        colors = []
        for family, embs in families.items():
            vals = []
            for embedding in embs:
                if embedding not in available:
                    continue
                for subject in SUBJECTS:
                    val = metric_value(subject, embedding, metric)
                    if np.isfinite(val):
                        vals.append(val)
            if not vals:
                continue
            vals = np.array(vals, dtype=np.float32)
            labels.append(family)
            means.append(float(vals.mean()))
            lows.append(float(vals.min()))
            highs.append(float(vals.max()))
            colors.append(family_colors[family])

        x = np.arange(len(labels))
        ax.bar(x, means, color=colors, edgecolor="white", linewidth=0.8)
        ax.errorbar(
            x,
            means,
            yerr=[np.array(means) - np.array(lows), np.array(highs) - np.array(means)],
            fmt="none",
            color="#222222",
            linewidth=1.2,
            capsize=4,
        )
        ax.set_xticks(x)
        ax.set_xticklabels(labels, rotation=15, ha="right")
        ax.set_ylabel("Pearson r")
        ax.set_title(METRIC_LABELS[metric], fontsize=12, fontweight="bold")
        ax.grid(True, axis="y", alpha=0.25)
        ax.grid(False, axis="x")
        for xi, val in zip(x, means):
            ax.text(xi, val + max(means) * 0.04, f"{val:.3f}", ha="center", fontsize=9)

    fig.suptitle("Performance by Embedding Family", fontsize=16, fontweight="bold")
    save_figure(fig, "fig5_embedding_family_summary")


def fig_subject_difference_summary():
    embeddings = available_embeddings(EMBEDDINGS_ALL)
    if len(SUBJECTS) < 2 or not embeddings:
        print("Skipping subject difference summary: need two subjects and stats.")
        return

    s2, s3 = "subject2", "subject3"
    fig, axes = plt.subplots(1, len(METRICS), figsize=(18, 4.8), constrained_layout=True)
    x = np.arange(len(embeddings))
    for ax, metric in zip(axes, METRICS):
        diffs = []
        for embedding in embeddings:
            diffs.append(metric_value(s3, embedding, metric) - metric_value(s2, embedding, metric))
        ax.axhline(0, color="#111111", linewidth=1.0)
        ax.bar(x, diffs, color=[COLORS[e] for e in embeddings], edgecolor="white", linewidth=0.7)
        ax.set_xticks(x)
        ax.set_xticklabels([EMBEDDING_LABELS[e] for e in embeddings], rotation=28, ha="right")
        ax.set_ylabel("Subject 3 - Subject 2")
        ax.set_title(METRIC_LABELS[metric], fontsize=12, fontweight="bold")
        ax.grid(True, axis="y", alpha=0.25)
        ax.grid(False, axis="x")
        for xi, val in zip(x, diffs):
            va = "bottom" if val >= 0 else "top"
            offset = 0.002 if val >= 0 else -0.002
            ax.text(xi, val + offset, f"{val:+.3f}", ha="center", va=va, fontsize=8)

    fig.suptitle("Subject Difference in Predictive Accuracy", fontsize=16, fontweight="bold")
    save_figure(fig, "fig5_subject_difference_summary")


def best_static_corrs(subject: str):
    static_corrs = []
    labels = []
    for embedding in ["glove", "word2vec"]:
        corrs = load_corrs(subject, embedding)
        if corrs is not None:
            static_corrs.append(np.asarray(corrs, dtype=np.float32))
            labels.append(EMBEDDING_LABELS[embedding])
    if not static_corrs:
        return None, None
    n = min(len(c) for c in static_corrs)
    arr = np.vstack([c[:n] for c in static_corrs])
    best_idx = np.argmax(arr, axis=0)
    best = arr[best_idx, np.arange(n)]
    return best.astype(np.float32), labels


def context_gain_values(subject: str, embedding: str):
    static, _ = best_static_corrs(subject)
    contextual = load_corrs(subject, embedding)
    if static is None or contextual is None:
        return None
    contextual = np.asarray(contextual, dtype=np.float32)
    n = min(len(static), len(contextual))
    return contextual[:n] - static[:n]


def fig_contextual_gain_over_static():
    embeddings = [e for e in BERT_METHODS if any(corrs_path(s, e).exists() for s in SUBJECTS)]
    if not embeddings:
        print("Skipping contextual gain summary: BERT correlation files are missing.")
        return

    fig, axes = plt.subplots(1, len(METRICS), figsize=(18, 4.8), constrained_layout=True)
    x = np.arange(len(SUBJECTS))
    width = 0.24
    offsets = np.linspace(-width, width, len(embeddings))

    for ax, metric in zip(axes, METRICS):
        for offset, embedding in zip(offsets, embeddings):
            vals = []
            for subject in SUBJECTS:
                static_vals = [
                    metric_value(subject, e, metric)
                    for e in ["glove", "word2vec"]
                    if np.isfinite(metric_value(subject, e, metric))
                ]
                contextual_val = metric_value(subject, embedding, metric)
                vals.append(contextual_val - max(static_vals) if static_vals and np.isfinite(contextual_val) else np.nan)
            bars = ax.bar(
                x + offset,
                vals,
                width=width,
                color=COLORS[embedding],
                edgecolor="white",
                linewidth=0.7,
                label=EMBEDDING_LABELS[embedding],
            )
            for bar, val in zip(bars, vals):
                if np.isfinite(val):
                    ax.text(
                        bar.get_x() + bar.get_width() / 2,
                        val + (0.002 if val >= 0 else -0.002),
                        f"{val:+.3f}",
                        ha="center",
                        va="bottom" if val >= 0 else "top",
                        fontsize=8,
                    )
        ax.axhline(0, color="#111111", linewidth=1.0)
        ax.set_xticks(x)
        ax.set_xticklabels([SUBJECT_LABELS[s] for s in SUBJECTS])
        ax.set_ylabel("Contextual gain over best static")
        ax.set_title(METRIC_LABELS[metric], fontsize=12, fontweight="bold")
        ax.grid(True, axis="y", alpha=0.25)
        ax.grid(False, axis="x")

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=len(embeddings), frameon=False, bbox_to_anchor=(0.5, -0.05))
    fig.suptitle("Contextual Embedding Gain Over Best Static Embedding", fontsize=16, fontweight="bold")
    save_figure(fig, "fig6_contextual_gain_over_static")


def fig_contextual_improvement_histograms():
    embeddings = [e for e in BERT_METHODS if all(corrs_path(s, e).exists() for s in SUBJECTS)]
    if not embeddings:
        print("Skipping contextual improvement histograms: missing BERT correlation files.")
        return

    fig, axes = plt.subplots(len(SUBJECTS), len(embeddings), figsize=(5.0 * len(embeddings), 7.5), sharex=True, constrained_layout=True)
    if len(SUBJECTS) == 1:
        axes = axes[None, :]
    bins = np.linspace(-0.10, 0.16, 90)

    for row, subject in enumerate(SUBJECTS):
        for col, embedding in enumerate(embeddings):
            ax = axes[row, col]
            gain = context_gain_values(subject, embedding)
            if gain is None:
                ax.set_visible(False)
                continue
            improved = 100.0 * float((gain > 0).mean())
            mean_gain = float(gain.mean())
            ax.hist(gain, bins=bins, density=True, color=COLORS[embedding], alpha=0.78)
            ax.axvline(0, color="#111111", linewidth=1.1)
            ax.axvline(mean_gain, color="#FFFFFF", linewidth=2.1)
            ax.axvline(mean_gain, color="#111111", linewidth=0.9, linestyle="--")
            ax.set_title(f"{SUBJECT_LABELS[subject]}: {EMBEDDING_LABELS[embedding]}", fontsize=11.5, fontweight="bold")
            ax.set_xlabel("Voxel CC gain over best static")
            ax.set_ylabel("Density")
            ax.text(
                0.03,
                0.93,
                f"mean={mean_gain:+.4f}\nimproved={improved:.1f}%",
                transform=ax.transAxes,
                va="top",
                fontsize=9,
                bbox={"facecolor": "white", "edgecolor": "#D9D9D9", "boxstyle": "round,pad=0.25"},
            )

    fig.suptitle("Voxel-Wise Contextual Improvement Over Static Embeddings", fontsize=16, fontweight="bold")
    save_figure(fig, "fig6_contextual_improvement_histograms")


def fig_contextual_percent_improved():
    embeddings = [e for e in BERT_METHODS if any(corrs_path(s, e).exists() for s in SUBJECTS)]
    if not embeddings:
        print("Skipping percent improved: missing BERT correlation files.")
        return

    fig, axes = plt.subplots(1, 2, figsize=(13.5, 5.0), constrained_layout=True)
    x = np.arange(len(embeddings))
    width = 0.34
    offsets = [-width / 2, width / 2]

    for ax, stat in zip(axes, ["percent", "mean"]):
        for offset, subject in zip(offsets, SUBJECTS):
            vals = []
            for embedding in embeddings:
                gain = context_gain_values(subject, embedding)
                if gain is None:
                    vals.append(np.nan)
                elif stat == "percent":
                    vals.append(100.0 * float((gain > 0).mean()))
                else:
                    vals.append(float(gain.mean()))
            ax.bar(
                x + offset,
                vals,
                width=width,
                color=["#89A8D8" if subject == "subject2" else "#D88989"][0],
                edgecolor="white",
                linewidth=0.7,
                label=SUBJECT_LABELS[subject],
                alpha=0.92,
            )
            for xi, val in zip(x + offset, vals):
                if np.isfinite(val):
                    text = f"{val:.1f}%" if stat == "percent" else f"{val:+.3f}"
                    ax.text(xi, val + (1.2 if stat == "percent" else 0.002), text, ha="center", fontsize=8)
        ax.set_xticks(x)
        ax.set_xticklabels([EMBEDDING_LABELS[e] for e in embeddings])
        ax.axhline(0, color="#111111", linewidth=1.0)
        if stat == "percent":
            ax.set_ylabel("Voxels improved over best static (%)")
            ax.set_ylim(0, 100)
            ax.set_title("Breadth of contextual improvement", fontsize=12, fontweight="bold")
        else:
            ax.set_ylabel("Mean voxel CC gain")
            ax.set_title("Average contextual lift", fontsize=12, fontweight="bold")
        ax.grid(True, axis="y", alpha=0.25)
        ax.grid(False, axis="x")

    axes[0].legend(frameon=False)
    fig.suptitle("How Often Do Contextual Embeddings Beat Static Embeddings?", fontsize=16, fontweight="bold")
    save_figure(fig, "fig6_contextual_percent_improved")


def fig_static_vs_contextual_scatter():
    embeddings = [e for e in BERT_METHODS if all(corrs_path(s, e).exists() for s in SUBJECTS)]
    if not embeddings:
        print("Skipping static-vs-contextual scatter: missing BERT correlations.")
        return

    fig, axes = plt.subplots(len(SUBJECTS), len(embeddings), figsize=(5.0 * len(embeddings), 8.8), constrained_layout=True)
    if len(SUBJECTS) == 1:
        axes = axes[None, :]

    for row, subject in enumerate(SUBJECTS):
        static, _ = best_static_corrs(subject)
        if static is None:
            for ax in axes[row, :]:
                ax.set_visible(False)
            continue
        for col, embedding in enumerate(embeddings):
            ax = axes[row, col]
            contextual = load_corrs(subject, embedding)
            if contextual is None:
                ax.set_visible(False)
                continue
            contextual = np.asarray(contextual, dtype=np.float32)
            n = min(len(static), len(contextual))
            x = static[:n]
            y = contextual[:n]
            lo = float(min(np.percentile(x, 0.2), np.percentile(y, 0.2)))
            hi = float(max(np.percentile(x, 99.8), np.percentile(y, 99.8)))
            pad = 0.08 * (hi - lo)
            lo -= pad
            hi += pad
            ax.hist2d(x, y, bins=90, range=[[lo, hi], [lo, hi]], cmap="Blues", cmin=1)
            ax.plot([lo, hi], [lo, hi], color="#E63946", linestyle="--", linewidth=1.1)
            improved = 100.0 * float((y > x).mean())
            ax.text(
                0.04,
                0.95,
                f"above diagonal={improved:.1f}%",
                transform=ax.transAxes,
                va="top",
                fontsize=9,
                bbox={"facecolor": "white", "edgecolor": "#D9D9D9", "boxstyle": "round,pad=0.25"},
            )
            ax.set_title(f"{SUBJECT_LABELS[subject]}: {EMBEDDING_LABELS[embedding]}", fontsize=11.5, fontweight="bold")
            ax.set_xlabel("Best static voxel CC")
            ax.set_ylabel("Contextual voxel CC")
            ax.set_xlim(lo, hi)
            ax.set_ylim(lo, hi)

    fig.suptitle("Static vs Contextual Embedding Performance by Voxel", fontsize=16, fontweight="bold")
    save_figure(fig, "fig6_static_vs_contextual_scatter")


def fig_top_voxel_contextual_lift(top_frac: float = 0.01):
    embeddings = [e for e in BERT_METHODS if all(corrs_path(s, e).exists() for s in SUBJECTS)]
    if not embeddings:
        print("Skipping top-voxel contextual lift: missing BERT correlations.")
        return

    fig, axes = plt.subplots(1, len(SUBJECTS), figsize=(7.2 * len(SUBJECTS), 5.2), sharey=True, constrained_layout=True)
    if len(SUBJECTS) == 1:
        axes = [axes]

    for ax, subject in zip(axes, SUBJECTS):
        static, _ = best_static_corrs(subject)
        if static is None:
            ax.set_visible(False)
            continue
        labels = []
        static_means = []
        contextual_means = []
        for embedding in embeddings:
            contextual = load_corrs(subject, embedding)
            if contextual is None:
                continue
            contextual = np.asarray(contextual, dtype=np.float32)
            n = min(len(static), len(contextual))
            k = max(1, int(np.floor(top_frac * n)))
            top = np.argsort(contextual[:n])[-k:]
            static_means.append(float(static[:n][top].mean()))
            contextual_means.append(float(contextual[:n][top].mean()))
            labels.append(EMBEDDING_LABELS[embedding])

        x = np.arange(len(labels))
        width = 0.34
        ax.bar(x - width / 2, static_means, width=width, color="#B9734D", edgecolor="white", label="Best static")
        ax.bar(x + width / 2, contextual_means, width=width, color="#4C86BD", edgecolor="white", label="Contextual")
        for xi, s_val, c_val in zip(x, static_means, contextual_means):
            ax.plot([xi - width / 2, xi + width / 2], [s_val, c_val], color="#333333", linewidth=1.0, alpha=0.65)
            ax.text(xi, max(s_val, c_val) + 0.004, f"+{c_val - s_val:.3f}", ha="center", fontsize=8.5)
        ax.set_xticks(x)
        ax.set_xticklabels(labels)
        ax.set_ylabel("Mean CC among contextual top 1% voxels")
        ax.set_title(SUBJECT_LABELS[subject], fontsize=13, fontweight="bold")
        ax.grid(True, axis="y", alpha=0.25)
        ax.grid(False, axis="x")
        ax.legend(frameon=False)

    fig.suptitle("Contextual Lift in the Best-Predicted Voxels", fontsize=16, fontweight="bold")
    save_figure(fig, "fig6_top_voxel_contextual_lift")


def fig_top_voxel_profiles():
    embeddings = available_embeddings(EMBEDDINGS_ALL)
    if not embeddings:
        print("Skipping CC profiles: no stats found.")
        return

    fig, axes = plt.subplots(1, len(SUBJECTS), figsize=(15, 7.3), sharey=True, constrained_layout=True)
    if len(SUBJECTS) == 1:
        axes = [axes]

    x = np.arange(len(embeddings))
    split_x = len(EMBEDDINGS_31) - 0.5 if all(e in embeddings for e in EMBEDDINGS_31) else None

    for ax, subject in zip(axes, SUBJECTS):
        means = np.array([metric_value(subject, e, "mean_cc") for e in embeddings])
        top5 = np.array([metric_value(subject, e, "top5_cc") for e in embeddings])
        top1 = np.array([metric_value(subject, e, "top1_cc") for e in embeddings])

        ax.bar(
            x,
            means,
            width=0.58,
            color=[COLORS[e] for e in embeddings],
            alpha=0.32,
            edgecolor="white",
            linewidth=0.7,
            label="Mean CC",
        )
        for xi, e, mean, p95 in zip(x, embeddings, means, top5):
            ax.vlines(xi, mean, p95, color=COLORS[e], linewidth=2.5, alpha=0.95)
            ax.plot([xi - 0.14, xi + 0.14], [p95, p95], color=COLORS[e], linewidth=2.5)
        ax.scatter(
            x,
            top1,
            marker="D",
            s=72,
            color=[COLORS[e] for e in embeddings],
            edgecolor="white",
            linewidth=0.8,
            zorder=4,
            label="Top 1% CC",
        )
        if split_x is not None:
            add_context_split(ax, split_x, orientation="vertical")

        ax.set_title(SUBJECT_LABELS[subject], fontsize=14, fontweight="bold")
        ax.set_xticks(x)
        ax.set_xticklabels([EMBEDDING_LABELS[e] for e in embeddings], rotation=32, ha="right")
        ax.set_xlabel("Embedding")
        ax.set_ylabel("Pearson correlation coefficient")
        ax.grid(True, axis="y", alpha=0.25)
        ax.grid(False, axis="x")
        ax.margins(y=0.16)

    handles = [
        Line2D([0], [0], color="#BDBDBD", linewidth=8, alpha=0.45, label="Mean CC (bar)"),
        Line2D([0], [0], color="#777777", linewidth=2.5, label="Stem = mean to top 5% CC"),
        Line2D([0], [0], marker="D", color="none", markerfacecolor="#777777", markeredgecolor="white",
               markersize=8, label="Top 1% CC"),
        Line2D([0], [0], color="#BDBDBD", linestyle="--", linewidth=1.2, label="Baseline/contextual split"),
    ]
    fig.legend(handles=handles, loc="lower center", ncol=4, frameon=True, bbox_to_anchor=(0.5, -0.05))
    fig.suptitle("CC Profile: Mean, Top 5%, and Top 1% per Embedding", fontsize=17, fontweight="bold")
    save_figure(fig, "fig3_top_voxel_profiles")


def fig_cross_subject_stability():
    embeddings = available_embeddings(EMBEDDINGS_32)
    if len(SUBJECTS) < 2 or not embeddings:
        print("Skipping cross-subject stability: need both subjects and Lab 3.2 outputs.")
        return

    metrics = ["mean_cc", "top5_cc", "top1_cc"]
    fig, axes = plt.subplots(1, 3, figsize=(13.5, 4.8), constrained_layout=True)

    for ax, metric in zip(axes, metrics):
        xs = []
        ys = []
        for embedding in embeddings:
            s2 = load_stats("subject2", embedding)
            s3 = load_stats("subject3", embedding)
            if s2 is None or s3 is None:
                continue
            x = s2[metric]
            y = s3[metric]
            xs.append(x)
            ys.append(y)
            ax.scatter(
                x,
                y,
                s=118,
                color=COLORS[embedding],
                edgecolor="white",
                linewidth=1.1,
                zorder=3,
            )
            ax.text(x, y, f"  {EMBEDDING_LABELS[embedding]}", va="center", fontsize=9.5)

        if xs and ys:
            lower = min(xs + ys) * 0.92
            upper = max(xs + ys) * 1.08
            ax.plot([lower, upper], [lower, upper], color="#111111", linewidth=1.0, alpha=0.55)
            ax.set_xlim(lower, upper)
            ax.set_ylim(lower, upper)
            if len(xs) > 1:
                r = float(np.corrcoef(xs, ys)[0, 1])
                ax.text(
                    0.04,
                    0.94,
                    f"method-level r = {r:.3f}",
                    transform=ax.transAxes,
                    va="top",
                    fontsize=9,
                    bbox={"facecolor": "white", "edgecolor": "#D9D9D9", "boxstyle": "round,pad=0.25"},
                )

        ax.set_title(METRIC_LABELS[metric], fontsize=12, fontweight="bold")
        ax.set_xlabel("Subject 2")
        ax.set_ylabel("Subject 3")
        ax.set_aspect("equal", adjustable="box")

    fig.suptitle("Cross-Subject Consistency of BERT Method Rankings", fontsize=16, fontweight="bold")
    save_figure(fig, "fig4_cross_subject_stability_bert")

    best = best_embedding_by_mean(embeddings)
    if best:
        for ext in ["png", "pdf"]:
            source = FIG_DIR / f"fig4_cross_subject_stability_bert.{ext}"
            alias = FIG_DIR / f"cross_subject_stability_{best}.{ext}"
            if source.exists():
                alias.write_bytes(source.read_bytes())
                print(f"Saved: {alias}")


def fig_voxel_cross_subject_density():
    embeddings = available_embeddings(EMBEDDINGS_32)
    if len(SUBJECTS) < 2 or not embeddings:
        print("Skipping voxel cross-subject density: need two subjects and Lab 3.2 corrs.")
        return

    fig, axes = plt.subplots(1, len(embeddings), figsize=(5.4 * len(embeddings), 5.1), constrained_layout=True)
    if len(embeddings) == 1:
        axes = [axes]

    for ax, embedding in zip(axes, embeddings):
        c2 = load_corrs("subject2", embedding)
        c3 = load_corrs("subject3", embedding)
        if c2 is None or c3 is None:
            ax.set_visible(False)
            continue

        c2 = np.asarray(c2, dtype=np.float32)
        c3 = np.asarray(c3, dtype=np.float32)
        n = min(c2.size, c3.size)
        c2 = c2[:n]
        c3 = c3[:n]

        lo = float(min(np.percentile(c2, 0.2), np.percentile(c3, 0.2)))
        hi = float(max(np.percentile(c2, 99.8), np.percentile(c3, 99.8)))
        pad = 0.08 * (hi - lo)
        lo -= pad
        hi += pad

        ax.hist2d(c2, c3, bins=90, range=[[lo, hi], [lo, hi]], cmap="Blues", cmin=1)
        ax.plot([lo, hi], [lo, hi], color="#E63946", linestyle="--", linewidth=1.15, label="y = x")
        r = float(np.corrcoef(c2, c3)[0, 1])
        ax.set_title(f"{EMBEDDING_LABELS[embedding]}\ninter-subject r = {r:.3f}", fontsize=12)
        ax.set_xlabel("Subject 2")
        ax.set_ylabel("Subject 3")
        ax.set_xlim(lo, hi)
        ax.set_ylim(lo, hi)
        ax.tick_params(axis="x", labelrotation=25)
        ax.legend(loc="upper right", frameon=True, fontsize=8)
        ax.grid(True, alpha=0.18)

    fig.suptitle("Cross-Subject Stability of Voxel-Wise CC", fontsize=16, fontweight="bold")
    save_figure(fig, "fig4_voxel_cross_subject_density_bert")


def fig_subject_consistency_all_embeddings():
    embeddings = available_embeddings(EMBEDDINGS_ALL)
    if len(SUBJECTS) < 2 or not embeddings:
        print("Skipping all-embedding subject consistency: need two subjects and stats.")
        return

    s2, s3 = "subject2", "subject3"
    fig, axes = plt.subplots(1, len(METRICS), figsize=(22, 6.2), constrained_layout=True)

    text_offsets = {
        "bow": (-0.010, 0.005),
        "glove": (0.008, 0.012),
        "word2vec": (0.010, -0.012),
        "bert_pretrained": (-0.016, 0.018),
        "bert_finetuned": (0.012, 0.004),
        "bert_lora": (-0.018, -0.020),
    }

    for ax, metric in zip(axes, METRICS):
        xs, ys = [], []
        for embedding in embeddings:
            x = metric_value(s2, embedding, metric)
            y = metric_value(s3, embedding, metric)
            if not np.isfinite(x) or not np.isfinite(y):
                continue
            xs.append(x)
            ys.append(y)
            ax.scatter(
                x,
                y,
                s=112,
                color=COLORS[embedding],
                edgecolor="white",
                linewidth=1.0,
                zorder=3,
            )

        if xs and ys:
            lower = min(xs + ys) * 0.84
            upper = max(xs + ys) * 1.12
            span = upper - lower
            ax.plot([lower, upper], [lower, upper], linestyle="--", color="#B5B5B5", linewidth=1.6)
            ax.set_xlim(lower, upper)
            ax.set_ylim(lower, upper)

            for embedding in embeddings:
                x = metric_value(s2, embedding, metric)
                y = metric_value(s3, embedding, metric)
                if not np.isfinite(x) or not np.isfinite(y):
                    continue
                ox, oy = text_offsets.get(embedding, (0.01, 0.01))
                ax.text(
                    x + ox * span,
                    y + oy * span,
                    EMBEDDING_LABELS[embedding],
                    color=COLORS[embedding],
                    fontsize=8.4,
                    fontweight="bold",
                    ha="left" if ox >= 0 else "right",
                    va="bottom" if oy >= 0 else "top",
                    bbox={"facecolor": "white", "edgecolor": "none", "alpha": 0.62, "pad": 0.15},
                )
        ax.set_title(METRIC_LABELS[metric], fontsize=12, fontweight="bold")
        ax.set_xlabel("Subject 2")
        ax.set_ylabel("Subject 3")
        ax.tick_params(axis="x", labelrotation=25)
        ax.grid(False)

    handles = [
        Line2D([0], [0], marker="o", color="none", label=EMBEDDING_LABELS[e],
               markerfacecolor=COLORS[e], markeredgecolor="white", markersize=8)
        for e in embeddings
    ]
    fig.legend(handles=handles, loc="lower center", ncol=len(embeddings), frameon=True, bbox_to_anchor=(0.5, -0.07))
    fig.suptitle("Subject Consistency: Subject 2 vs Subject 3", fontsize=17, fontweight="bold")
    save_figure(fig, "fig4_subject_consistency")


def best_embedding_by_mean(embeddings):
    best_embedding = None
    best_value = -np.inf
    for embedding in embeddings:
        vals = []
        for subject in SUBJECTS:
            stats = load_stats(subject, embedding)
            if stats:
                vals.append(stats["mean_cc"])
        if vals and float(np.mean(vals)) > best_value:
            best_value = float(np.mean(vals))
            best_embedding = embedding
    return best_embedding


def main():
    print(f"RESULTS_DIR: {RESULTS_DIR}")
    print(f"FIG_DIR:     {FIG_DIR}")

    write_metric_tables()

    # Lab 3.1-style summary figures for Lab 3.2 BERT variants.
    fig_bert_metric_summary()
    fig_bert_voxel_distributions()
    fig_cross_subject_stability()
    fig_voxel_cross_subject_density()

    # All-embedding figures for the full report comparison.
    fig_all_embeddings_hbars()
    fig_all_embedding_comparison()
    fig_top_voxel_profiles()
    fig_subject_consistency_all_embeddings()

    # Additional Lab 3.2 diagnostics.
    fig_bert_delta_from_pretrained()
    fig_well_predicted_voxel_overlap()
    fig_finetuning_win_loss_summary()
    fig_pretrained_vs_finetuned_scatter()
    fig_top_voxel_rank_stability()
    fig_alpha_distributions()
    fig_embedding_family_summary()
    fig_subject_difference_summary()
    fig_contextual_gain_over_static()
    fig_contextual_improvement_histograms()
    fig_contextual_percent_improved()
    fig_static_vs_contextual_scatter()
    fig_top_voxel_contextual_lift()

    print("\nDone.")


if __name__ == "__main__":
    main()
